//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Ticaret_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BedenvsUrun
    {
        public int GecisID { get; set; }
        public Nullable<int> BedenID { get; set; }
        public Nullable<int> UrunID { get; set; }
    
        public virtual Bedenler Bedenler { get; set; }
        public virtual Urunler Urunler { get; set; }
    }
}
