//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Ticaret_MVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EShopperEntities : DbContext
    {
        public EShopperEntities()
            : base("name=EShopperEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bedenler> Bedenler { get; set; }
        public virtual DbSet<BedenvsUrun> BedenvsUrun { get; set; }
        public virtual DbSet<FaturaDetay> FaturaDetay { get; set; }
        public virtual DbSet<Faturalar> Faturalar { get; set; }
        public virtual DbSet<Gorseller> Gorseller { get; set; }
        public virtual DbSet<Kategori> Kategori { get; set; }
        public virtual DbSet<Markalar> Markalar { get; set; }
        public virtual DbSet<Musteriler> Musteriler { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Urunler> Urunler { get; set; }
        public virtual DbSet<Yorumlar> Yorumlar { get; set; }
        public virtual DbSet<kampanya> kampanya { get; set; }
        public virtual DbSet<v_VitrinUrunler> v_VitrinUrunler { get; set; }
    }
}
