//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Ticaret_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_VitrinUrunler
    {
        public int UrunID { get; set; }
        public string UrunAdi { get; set; }
        public string UrunAciklama { get; set; }
        public Nullable<int> KategoriID { get; set; }
        public Nullable<System.DateTime> VitrineCikisTarih { get; set; }
        public Nullable<int> MarkaID { get; set; }
        public Nullable<decimal> BirimFiyat { get; set; }
        public Nullable<int> GirenAdet { get; set; }
        public Nullable<int> CikanAdet { get; set; }
        public Nullable<int> NetAdet { get; set; }
        public string ResimUrl { get; set; }
    }
}
