//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Ticaret_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yorumlar
    {
        public Nullable<int> UrunId { get; set; }
        public int YorumID { get; set; }
        public string Yorum { get; set; }
        public string Rate { get; set; }
        public string yorumcu { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
    
        public virtual Urunler Urunler { get; set; }
    }
}
